#pragma once

namespace sdk
{
	enum trace_type
	{
		TRACE_EVERYTHING = 0,
		TRACE_WORLD_ONLY,
		TRACE_ENTITIES_ONLY,
		TRACE_EVERYTHING_FILTER_PROPS,
	};

	enum contents
	{
		CONTENTS_EMPTY                = 0X0,
		CONTENTS_SOLID                = 0X1,
		CONTENTS_WINDOW               = 0X2,
		CONTENTS_AUX                  = 0X4,
		CONTENTS_GRATE                = 0X8,
		CONTENTS_SLIME                = 0X10,
		CONTENTS_WATER                = 0X20,
		CONTENTS_BLOCKLOS             = 0X40,
		CONTENTS_OPAQUE               = 0X80,
		CONTENTS_TESTFOGVOLUME        = 0X100,
		CONTENTS_UNUSED               = 0X200,
		CONTENTS_BLOCKLIGHT           = 0X400,
		CONTENTS_TEAM1                = 0X800,
		CONTENTS_TEAM2                = 0X1000,
		CONTENTS_IGNORE_NODRAW_OPAQUE = 0X2000,
		CONTENTS_MOVEABLE             = 0X4000,
		CONTENTS_AREAPORTAL           = 0X8000,
		CONTENTS_PLAYERCLIP           = 0X10000,
		CONTENTS_MONSTERCLIP          = 0X20000,
		CONTENTS_CURRENT0             = 0X40000,
		CONTENTS_CURRENT90            = 0X80000,
		CONTENTS_CURRENT180           = 0X100000,
		CONTENTS_CURRENT270           = 0X200000,
		CONTENTS_CURRENT_UP           = 0X400000,
		CONTENTS_CURRENT_DOWN         = 0X800000,
		CONTENTS_ORIGIN               = 0X1000000,
		CONTENTS_MONSTER              = 0X2000000,
		CONTENTS_DEBRIS               = 0X4000000,
		CONTENTS_DETAIL               = 0X8000000,
		CONTENTS_TRANSLUCENT          = 0X10000000,
		CONTENTS_LADDER               = 0X20000000,
		CONTENTS_HITBOX               = 0X40000000,

		LAST_VISIBLE_CONTENTS = CONTENTS_OPAQUE,
		ALL_VISIBLE_CONTENTS  = LAST_VISIBLE_CONTENTS | LAST_VISIBLE_CONTENTS - 1
	};

	enum masks
	{
		MASK_ALL             = 0XFFFFFFFF,
		MASK_SOLID           = ( CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_WINDOW | CONTENTS_MONSTER | CONTENTS_GRATE ),
		MASK_PLAYERSOLID     = ( CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_PLAYERCLIP | CONTENTS_WINDOW | CONTENTS_MONSTER | CONTENTS_GRATE ),
		MASK_NPCSOLID        = ( CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_MONSTERCLIP | CONTENTS_WINDOW | CONTENTS_MONSTER | CONTENTS_GRATE ),
		MASK_NPCFLUID        = ( CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_MONSTERCLIP | CONTENTS_WINDOW | CONTENTS_MONSTER ),
		MASK_WATER           = ( CONTENTS_WATER | CONTENTS_MOVEABLE | CONTENTS_SLIME ),
		MASK_OPAQUE          = ( CONTENTS_WATER | CONTENTS_MOVEABLE | CONTENTS_OPAQUE ),
		MASK_OPAQUE_NPC      = ( MASK_OPAQUE | CONTENTS_MONSTER ),
		MASK_BLOCKLOS        = ( CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_SLIME ),
		MASK_BLOCKLOS_NPC    = ( MASK_BLOCKLOS | CONTENTS_MONSTER ),
		MASK_VISIBLE         = ( MASK_OPAQUE | CONTENTS_IGNORE_NODRAW_OPAQUE ),
		MASK_VISIBLE_NPC     = ( MASK_OPAQUE_NPC | CONTENTS_IGNORE_NODRAW_OPAQUE ),
		MASK_SHOT            = ( CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_MONSTER | CONTENTS_WINDOW | CONTENTS_DEBRIS | CONTENTS_HITBOX ),
		MASK_SHOT_BRUSHONLY  = ( CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_WINDOW | CONTENTS_DEBRIS ),
		MASK_SHOT_HULL       = ( CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_MONSTER | CONTENTS_WINDOW | CONTENTS_DEBRIS | CONTENTS_GRATE ),
		MASK_SHOT_PLAYER     = ( MASK_SHOT_HULL | CONTENTS_HITBOX ),
		MASK_SHOT_PORTAL     = ( CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_WINDOW | CONTENTS_MONSTER ),
		MASK_SOLID_BRUSHONLY = ( CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_WINDOW | CONTENTS_GRATE ),
		MASK_PLAYERSOLID_BRUSHONLY = ( CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_WINDOW | CONTENTS_PLAYERCLIP | CONTENTS_GRATE ),
		MASK_NPCSOLID_BRUSHONLY    = ( CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_WINDOW | CONTENTS_MONSTERCLIP | CONTENTS_GRATE ),
		MASK_NPCWORLDSTATIC        = ( CONTENTS_SOLID | CONTENTS_WINDOW | CONTENTS_MONSTERCLIP | CONTENTS_GRATE ),
		MASK_NPCWORLDSTATIC_FLUID  = ( CONTENTS_SOLID | CONTENTS_WINDOW | CONTENTS_MONSTERCLIP ),
		MASK_SPLITAREAPORTAL       = ( CONTENTS_WATER | CONTENTS_SLIME ),
		MASK_CURRENT =
			( CONTENTS_CURRENT0 | CONTENTS_CURRENT90 | CONTENTS_CURRENT180 | CONTENTS_CURRENT270 | CONTENTS_CURRENT_UP | CONTENTS_CURRENT_DOWN ),
		MASK_DEADSOLID = ( CONTENTS_SOLID | CONTENTS_PLAYERCLIP | CONTENTS_WINDOW | CONTENTS_GRATE )
	};
} // namespace sdk
